default_context:
  description: MkDocs is a fast, simple and downright gorgeous static site generator
    that's geared towards building project documentation.
  feature_name: MkDocs (via pipx)
  feature_id: mkdocs
  test_command: mkdocs --version
  gitrepo: http://github.com/devcontainers-contrib/features
  content:
    pipx:
    - package_name: mkdocs
      display_name: MKDocs
      version_alias: version
      default: latest
      exposed: true
      optional: false
      injections:
      - package_name: mkdocs-material
        display_name: mkdocs-material-plugin
        default: latest
        exposed: true
        optional: true
      - package_name: pymdown-extensions
        display_name: pymdown-extensions-plugin
        default: none
        exposed: true
        optional: true
      - package_name: mkdocstrings[crystal,python]
        display_name: mkdocstrings-plugin
        default: none
        exposed: true
        optional: true
      - package_name: mkdocs-monorepo-plugin
        display_name: mkdocs-monorepo-plugin
        default: none
        exposed: true
        optional: true
      - package_name: mkdocs-pdf-export-plugin
        display_name: mkdocs-pdf-export-plugin
        default: none
        exposed: true
        optional: true
      - package_name: mkdocs-awesome-pages-plugin
        display_name: mkdocs-awesome-pages-plugin
        default: none
        exposed: true
        optional: true
    aptget: []