name: "Generate features"
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "install generator"
        run: |
          pipx install cookiecutter
          pipx install shfmt-py
      - name: Create PR for Features
        id: push_image_info
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_PAT }}
        run: |
          set -e
          echo "Start."
          # Configure git and Push updates
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git config pull.rebase false
          branch=releases/automated-feature-generation-$GITHUB_RUN_ID
          git checkout -b $branch
          message='Automated feature generation'
          # Generate
          cd ..
          for d in ./features/feature_specs/* ; do  cookiecutter ./features/pkgs/feature-template --overwrite-if-exists --no-input --config-file "$d"; done
          cd features
          # Add / update and commit
          git add src/**/\*
          git add test/**/\*
          git commit -m 'Automated feature generation' || export NO_UPDATES=true
          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "$message" --body "$message"
          fi
