name: "test features - (changes only)"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  find-feature:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    name: Find changed features
    outputs:
      changed_features: ${{ steps.feature-specs.outputs.changed_features }}

    steps:
      - uses: actions/checkout@v3
      - id: feature-specs
        uses: ./.github/actions/list-changed-features-action
        with:
          path: .

  test:
    needs: [find-feature]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJson( needs.find-feature.outputs.changed_features )}}
        baseImage: ["mcr.microsoft.com/devcontainers/base:debian"]

    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
